### ISSUE TITLE
 name not matched: runapi默认项目/*

### ISSUE THREAD

**Issue by goyeee** [FGadvancer/ruapi-generate-md#1]
按照说明执行 ：./start_and_zip.sh runapi默认项目 ，提示错误。
请问什么原因？

clone目录: /showdoc_data/ruapi-generate-md

![image](https://user-images.githubusercontent.com/45221885/233908093-e0fedb5f-5eb1-40ce-9ba0-e05adf5c8b48.png)
![image](https://user-images.githubusercontent.com/45221885/233908203-794c574b-4003-4737-b3d0-0e5122fb18d4.png)

**Comment by FGadvancer** [comment]
you can try to exec follow code to install sqlite3.（because this program need to read showdoc's sqlite3 file）
```
sudo apt-get install sqlite3 libsqlite3-dev
```
any questions, can contact me again.

**Comment by goyeee** [comment]
谢谢回复。但我还是遇到了问题。
我的系统为CentOs: CentOS Linux release 8.2.2004 (Core)
我尝试了以下操作，提示command not found
`[root@iZ2ze51b0olodvsuw3tvg0Z ruapi-generate-md]# apt-get install
-bash: apt-get: command not found`  

接下来：
`[root@iZ2ze51b0olodvsuw3tvg0Z ruapi-generate-md]# yum install yum install libsqlite3-dev
Repository epel is listed more than once in the configuration
Last metadata expiration check: 1:48:42 ago on Mon 24 Apr 2023 09:46:39 PM CST.
Package yum-4.2.17-7.el8_2.noarch is already installed.
No match for argument: install
No match for argument: libsqlite3-dev
Error: Unable to find a match: install libsqlite3-dev`

然后：成功安装 libsqlite3x-devel.x86_64
`yum install libsqlite3x-devel.x86_64`

最后：和最初的结果好像差不多
`[root@iZ2ze51b0olodvsuw3tvg0Z ruapi-generate-md]# ./start_and_zip.sh runapi默认项目
generate start at  2023-04-24 23:31:16.397642449 +0800 CST m=+0.001715005
当前代码执行目录的上一级目录为：.
panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
github.com/ruapi-generate-md/pkg/db.(*DataBase).Init(0xc000132900)
        /Users/gordon/GolandProjects/private/ruapi-generate-md/pkg/db/db_init.go:27 +0x314
github.com/ruapi-generate-md/internal.GeneratePageByItemID({0x66245c, 0x2}, {0x7fff99146746, 0x12})
        /Users/gordon/GolandProjects/private/ruapi-generate-md/internal/catlaog_page_generator.go:18 +0x85
main.main()
        /Users/gordon/GolandProjects/private/ruapi-generate-md/cmd/main.go:26 +0x1d6
        zip warning: name not matched: runapi默认项目/*

zip error: Nothing to do! (try: zip -r runapi默认项目.zip . -i runapi默认项目/*)`

**Comment by FGadvancer** [comment]
I have rebuild a binary code use cgo and push to branch of main, you can git pull update this project and try again.

**Comment by goyeee** [comment]
可以生成了！非常感谢！

但是，还是有些不完美。比如：
1. “/” 目录下的项目没有出现在 .zip 中
2. 目录层级没有原本复现。
请见以下截图。

我的目录层级：
![image](https://user-images.githubusercontent.com/45221885/234628973-92de72fa-153a-41d6-882f-a8f9e2d84a08.png)

.md 生成情况:
![image](https://user-images.githubusercontent.com/45221885/234628557-0be53057-cb0d-4355-8fa3-cdb7db131000.png)

其他问题1：
![image](https://user-images.githubusercontent.com/45221885/234629974-12dd1a6a-f386-4503-b473-421500883286.png)

其他问题2：
![image](https://user-images.githubusercontent.com/45221885/234630113-c0435f24-c3ae-4e39-8da6-7bb7a75f694a.png)

Thanks，怎样请你喝杯coffee?

**Comment by FGadvancer** [comment]
Thanks for your feedback. I have fixed the problem,try to generate md file recursively, some problems of fomat,maybe just in your viewer, try use VsCode or Typora to show this md file and you must ensure global header set correctly about your first question.

**Comment by goyeee** [comment]
感谢帮助。
“/”  的问题验证被修复。
格式的问题我研究一下你的源码，自己搞定，顺便学习一下。
